/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._

object $_scalate_$_banner_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      implicit val context: _root_.org.fusesource.scalate.servlet.ServletRenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n        <tr>\r\n          <td align=\"left\" class=\"topbardiv\" nowrap=\"\">\r\n<a href=\"http://karaf.apache.org/\" title=\"A server side OSGi distribution\">\r\n            <img border=\"0\" src=\"" );
      $_scalate_$_context <<< (       uri("/images/karaf-logo.png")
 );
      $_scalate_$_context << ( "\" width=\"400px\"></img>\r\n</a>\r\n          </td>\r\n          <td align=\"right\" nowrap=\"\">\r\n<a href=\"http://www.apache.org/\" title=\"The Apache Sofware Foundation\">\r\n            <img border=\"0\" src=\"" );
      $_scalate_$_context <<< (       uri("/images/asf-logo.png")
 );
      $_scalate_$_context << ( "\">\r\n</a>\r\n          </td>\r\n        </tr>\r\n      </table>\r\n" );
    }
  }
}


class $_scalate_$_banner_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$_banner_ssp.$_scalate_$render(context)
}
