/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._

object $_scalate_$_quicklinks_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      implicit val context: _root_.org.fusesource.scalate.servlet.ServletRenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      $_scalate_$_context << ( "<p>\r\n<a href=\"" );
      $_scalate_$_context <<< (       uri("/index.html")
 );
      $_scalate_$_context << ( "\" title=\"Home\">Home</a>\r\n&#124;\r\n<a href=\"" );
      $_scalate_$_context <<< (       uri("/users-guide/index.html")
 );
      $_scalate_$_context << ( "\" title=\"Users Guide\">Users Guide</a>\r\n&#124;\r\n<a href=\"" );
      $_scalate_$_context <<< (       uri("/developers-guide/index.html")
 );
      $_scalate_$_context << ( "\" title=\"Developers Guide\">Developers Guide</a>\r\n</p>\r\n\r\n" );
    }
  }
}


class $_scalate_$_quicklinks_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$_quicklinks_ssp.$_scalate_$render(context)
}
